const products=[
 {id:'horizontal-south',name:'42″ Horizontal Band Saw Machine (South)',cat:'machine',type:'Horizontal bandsaw',desc:'Heavy-duty Excel system for high-volume timber cutting.',images:['assets/products/horizontal-south/horizontal-south-1.png','assets/products/horizontal-south/horizontal-south-2.png','assets/products/horizontal-south/horizontal-south-3.png','assets/products/horizontal-south/horizontal-south-4.png'],spec:[['Pillar height','7 Ft.'],['Cutting capacity','Height: 3.6 Ft. (42″), Breadth: 5.5 Ft. (66″)'],['System','Heavy Duty Excel System'],['Wheel size','42″'],['Wheel thickness','23 mm'],['Trolley size','10–18 Ft. × 4 Ft.'],['Lift system','Gear & Motor (any one choice)'],['Lift motor','2 HP – 960 RPM'],['Motor','15 HP – 960 RPM'],['Ideal for','Log, hardwood, MDF, softwood, plywood']]},
 {id:'horizontal-local',name:'42″ Horizontal Band Saw Machine (Local)',cat:'machine',type:'Horizontal bandsaw',desc:'Precision cutting machine configured for local industrial operations.',images:['assets/products/horizontal-local/horizontal-local-1.png','assets/products/horizontal-local/horizontal-local-2.png','assets/products/horizontal-local/horizontal-local-3.png','assets/products/horizontal-local/horizontal-local-4.png','assets/products/horizontal-local/horizontal-local-5.png'],spec:[['Pillar height','7 Ft.'],['Cutting capacity','Height: 3.6 Ft. (42″), Breadth: 5.5 Ft. (66″)'],['System','Heavy Duty Excel System'],['Wheel size','42″'],['Wheel thickness','23 mm'],['Trolley size','Length: 10 Ft., Breadth: 4 Ft., wheel size: 8″'],['Trolley rail','70 Ft.'],['Lift system','Gear & Motor (any one choice)'],['Lift motor','2 HP – 960 RPM'],['Motor','15 HP – 960 RPM'],['Ideal for','Log, hardwood, MDF, softwood, plywood']]},
 {id:'vertical12',name:'42″ Vertical Band Saw Machine (12″ × 12″ Body)',cat:'machine',type:'Vertical bandsaw',desc:'Compact heavy-duty vertical bandsaw for precise wood processing.',images:['assets/products/vertical12/vertical12-1.png','assets/products/vertical12/vertical12-2.png','assets/products/vertical12/vertical12-3.png','assets/products/vertical12/vertical12-4.png','assets/products/vertical12/vertical12-5.png'],spec:[['Machine name','42″ Vertical Band Saw Machine (12″ × 12″ Body)'],['Body size','12″ × 12″ body; Height: 7.9 Ft., Breadth: 1.8 Ft., Length: 5 Ft.'],['Type','Vertical Band Saw'],['System','Heavy Duty Excel System'],['Wheel size','42″'],['Wheel thickness','23 mm'],['Table size','42″ × 42″'],['Motor','15 HP – 960 RPM'],['Ideal for','Hardwood, MDF, softwood, plywood']]},
 {id:'vertical16',name:'42″ Vertical Band Saw Machine (16″ × 16″ Body)',cat:'machine',type:'Vertical bandsaw',desc:'Robust large-body vertical machine for smooth, accurate cutting.',images:['assets/products/vertical16/vertical16-1.png','assets/products/vertical16/vertical16-2.png','assets/products/vertical16/vertical16-3.png','assets/products/vertical16/vertical16-4.png'],spec:[['Machine name','42″ Vertical Band Saw Machine (16″ × 16″ Body)'],['Body size','16″ × 16″ body; Height: 8 Ft., Breadth: 2 Ft., Length: 5.5 Ft.'],['Type','Vertical Band Saw'],['System','Heavy Duty Excel System'],['Wheel size','42″'],['Wheel thickness','23 mm'],['Table size','42″ × 42″'],['Motor','15 HP – 960 RPM'],['Ideal for','Hardwood, MDF, softwood, plywood']]},
 {id:'circular',name:'Circular Machine',cat:'machine',type:'Wood cutting machine',desc:'Industrial circular machine solution. Contact us for specifications and configuration.',images:['assets/products/Circular machine/ChatGPT Image Jul 19, 2026, 12_27_50 AM.png','assets/products/Circular machine/ChatGPT Image Jul 19, 2026, 12_27_57 AM.png','assets/products/Circular machine/ChatGPT Image Jul 19, 2026, 12_28_06 AM.png','assets/products/Circular machine/ChatGPT Image Jul 19, 2026, 12_28_30 AM.png'],spec:[['Category','Industrial wood cutting machine'],['Availability','Made to order'],['Support','Installation, genuine parts and servicing'],['Inquiry','Contact our team for complete specification']]},
 {id:'log-puller',name:'Log Puller Machine',cat:'machine',type:'Material handling',desc:'Log handling attachment for reliable timber movement and workflow support.',images:['assets/products/Log Puller/ChatGPT Image Jul 19, 2026, 12_41_36 AM.png'],spec:[['Category','Log handling equipment'],['Availability','Made to order'],['Support','Genuine parts and servicing available'],['Inquiry','Contact our team for complete specification']]}
];
const card=p=>`<article class="product-card" data-cat="${p.cat}" data-text="${(p.name+' '+p.type+' '+p.desc).toLowerCase()}"><div class="image-slider"><span class="tag">${p.cat==='spare'?'Spare part':'Machine'}</span>${p.images.map(x=>`<img src="${x}" alt="${p.name}">`).join('')}</div><div class="card-copy"><p>${p.type}</p><h3>${p.name}</h3><button onclick="showProduct('${p.id}')">View details & specifications →</button></div></article>`;
const catalogEl=document.getElementById('catalog-products');const featuredEl=document.getElementById('featured-products');const productSelect=document.getElementById('product-select');
if(catalogEl)catalogEl.innerHTML=products.map(card).join('');if(featuredEl)featuredEl.innerHTML=products.slice(0,3).map(card).join('');
if(productSelect)productSelect.innerHTML='<option value="">Select a product / service</option>'+products.map(p=>`<option>${p.name}</option>`).join('')+'<option>Genuine spare parts</option><option>Maintenance & servicing</option>';
function showProduct(id){const p=products.find(x=>x.id===id),d=document.getElementById('product-detail');d.innerHTML=`<button class="detail-back" onclick="closeProduct()">← Back to product catalogue</button><div class="detail-layout"><div><div class="gallery-main" id="main-gallery"><img id="main-image" src="${p.images[0]}" alt="${p.name}"><span class="gallery-hint">Move cursor to zoom</span></div><div class="thumbs">${p.images.map((x,i)=>`<button class="${i===0?'active':''}" onclick="selectImage('${x}',this)"><img src="${x}" alt="${p.name} view ${i+1}"></button>`).join('')}</div></div><div class="detail-info"><p class="eyebrow">${p.type}</p><h2>${p.name}</h2><p>${p.desc}</p><button class="btn primary" onclick="inquire('${p.name.replace(/'/g,"\\'")}')">Make an inquiry <span>→</span></button><table class="spec-table"><tbody>${p.spec.map(s=>`<tr><th>${s[0]}</th><td>${s[1]}</td></tr>`).join('')}</tbody></table></div></div>`;d.hidden=false;d.scrollIntoView({behavior:'smooth',block:'start'});const g=document.getElementById('main-gallery');g.addEventListener('mousemove',e=>{const r=g.getBoundingClientRect();g.style.setProperty('--x',`${(e.clientX-r.left)/r.width*100}%`);g.style.setProperty('--y',`${(e.clientY-r.top)/r.height*100}%`);g.classList.add('zoom')});g.addEventListener('mouseleave',()=>g.classList.remove('zoom'));}
function selectImage(src,el){document.getElementById('main-image').src=src;document.querySelectorAll('.thumbs button').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
function closeProduct(){document.getElementById('product-detail').hidden=true;document.getElementById('products').scrollIntoView({behavior:'smooth'})}
function inquire(name){if(productSelect)productSelect.value=name;location.href='inquiry.html'}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');applyFilters()}));const searchEl=document.getElementById('search');if(searchEl)searchEl.addEventListener('input',applyFilters);function applyFilters(){if(!searchEl)return;const q=searchEl.value.toLowerCase(),f=document.querySelector('.filter.active').dataset.filter;document.querySelectorAll('#catalog-products .product-card').forEach(c=>c.style.display=((f==='all'||c.dataset.cat===f)&&c.dataset.text.includes(q))?'flex':'none')}
const inquiryForm=document.getElementById('inquiry-form');if(inquiryForm)inquiryForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),body=`Name: ${f.get('name')}%0APhone: ${f.get('phone')}%0AEmail: ${f.get('email')}%0AProduct / Service: ${f.get('product')}%0A%0ARequirement:%0A${f.get('message')}`;location.href=`mailto:office.laxmieng83@gmail.com?subject=Laxmi Engineering Inquiry&body=${body}`});const menu=document.querySelector('.menu');if(menu)menu.addEventListener('click',e=>{e.currentTarget.classList.toggle('open')});document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>menu&&menu.classList.remove('open')));
