const selectedId=new URLSearchParams(location.search).get('id');
const selectedProduct=products.find(product=>product.id===selectedId)||products[0];
const specificationHost=document.getElementById('specification-host');
function specificationMarkup(product){return `<section class="product-detail spec-page"><a class="detail-back" href="products.html">← Back to products</a><div class="detail-layout"><div><div class="gallery-main" id="spec-gallery"><img id="spec-image" src="${product.images[0]}" alt="${product.name}"><button class="gallery-glass gallery-prev" aria-label="Previous image">‹</button><button class="gallery-glass gallery-next" aria-label="Next image">›</button><span class="gallery-hint">Move cursor to zoom</span></div><div class="thumbs">${product.images.map((image,index)=>`<button class="${index===0?'active':''}" data-image="${image}"><img src="${image}" alt="${product.name} view ${index+1}"></button>`).join('')}</div></div><div class="detail-info"><p class="eyebrow">${product.type}</p><h1>${product.name}</h1><p>${product.desc}</p><a class="btn primary" href="inquiry.html?product=${encodeURIComponent(product.name)}">Make an inquiry <span>→</span></a><table class="spec-table"><tbody>${product.spec.map(item=>`<tr><th>${item[0]}</th><td>${item[1]}</td></tr>`).join('')}</tbody></table></div></div></section>`}
specificationHost.innerHTML=specificationMarkup(selectedProduct);
const specImages=selectedProduct.images;let specCurrent=0;const specImage=document.getElementById('spec-image');
function setSpecImage(index){specCurrent=(index+specImages.length)%specImages.length;specImage.src=specImages[specCurrent];document.querySelectorAll('.thumbs button').forEach((button,i)=>button.classList.toggle('active',i===specCurrent))}
document.querySelector('.gallery-prev').onclick=()=>setSpecImage(specCurrent-1);document.querySelector('.gallery-next').onclick=()=>setSpecImage(specCurrent+1);document.querySelectorAll('.thumbs button').forEach((button,index)=>button.onclick=()=>setSpecImage(index));
const zoomGallery=document.getElementById('spec-gallery');zoomGallery.addEventListener('mousemove',event=>{const rect=zoomGallery.getBoundingClientRect();zoomGallery.style.setProperty('--x',`${(event.clientX-rect.left)/rect.width*100}%`);zoomGallery.style.setProperty('--y',`${(event.clientY-rect.top)/rect.height*100}%`);zoomGallery.classList.add('zoom')});zoomGallery.addEventListener('mouseleave',()=>zoomGallery.classList.remove('zoom'));
let touchStart=0;zoomGallery.addEventListener('touchstart',event=>touchStart=event.changedTouches[0].screenX,{passive:true});zoomGallery.addEventListener('touchend',event=>{const delta=event.changedTouches[0].screenX-touchStart;if(Math.abs(delta)>35)setSpecImage(specCurrent+(delta<0?1:-1))},{passive:true});
